
namespace Font {
    constant ZERO                    = 0x01
    constant CAPITAL_A               = 0x0b
    constant SPACE                   = 0x5f
    constant NEW_LINE                = 0x60
    constant COLON                   = 0x4e
    constant FIRST_INVALID_CHARACTER = 0x61

    // String mapping
    map '0', 0x01, 10
    map 'A', 0x0b, 26
    map 'a', 0x25, 26
    map '!', 0x3f, 15
    map ':', 0x4e, 7
    map '[', 0x55, 6
    map '{', 0x5b, 4
    map ' ', 0x5f
    map '\n', 0x60
}

